version: '3.8'

services:
  docker-dind:
    env_file:
      - .env.jenkins

    image: docker:dind
    container_name: jenkins-docker
    restart: unless-stopped
    privileged: true

    environment:
      - DOCKER_TLS_CERTDIR=${DOCKER_TLS_CERTDIR}

    volumes:
      - jenkins_docker_certs:/certs/client
      - jenkins_data:/var/jenkins_home

    networks:
      jenkins-network:
        aliases:
          - docker

    command: --storage-driver=${DOCKER_STORAGE_DRIVER}

  jenkins:
    env_file:
      - .env.jenkins

    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    user: root

    ports:
      - '${JENKINS_WEB_PORT}:8080'
      - '${JENKINS_AGENT_PORT}:50000'

    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_CERT_PATH=${DOCKER_CERT_PATH}
      - DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}

    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro

    networks:
      - jenkins-network

    depends_on:
      - docker-dind

volumes:
  jenkins_data:
  jenkins_docker_certs:

networks:
  jenkins-network:
    driver: bridge
