services:
  docker-dind:
    image: docker:dind
    privileged: true
    container_name: docker-dind
    restart: unless-stopped

    environment:
      DOCKER_TLS_CERTDIR: /certs

    volumes:
      - ./docker-dind/docker-certs-ca:/certs/ca
      - ./docker-dind/docker-certs-client:/certs/client
      - jenkins-docker-data:/var/lib/docker

    networks:
      jenkins-network:
        aliases:
          - docker
    healthcheck:
      test: ['CMD', 'docker', 'info']
      interval: 10s
      timeout: 5s
      retries: 5

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped

    depends_on:
      docker-dind:
        condition: service_healthy

    ports:
      - '${JENKINS_WEB_PORT}:8080'
      - '${JENKINS_AGENT_PORT}:50000'

    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1

    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./docker-dind/docker-certs-client:/certs/client:ro

    networks:
      - jenkins-network

volumes:
  jenkins-docker-data:

networks:
  jenkins-network:
    driver: bridge
