services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    restart: unless-stopped

    env_file:
      - .env.jenkins

    ports:
      - '${JENKINS_WEB_PORT}:8080'
      - '${JENKINS_AGENT_PORT}:50000'

    volumes:
      - ./jenkins_home:/var/jenkins_home:z

    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
